### PR TITLE
Adding a tagline for Forklift

### PR DESCRIPTION
**Pull request by ehelms**
Trying out a tag line..... now we just need a solid icon per @stbenjam prior suggestion.

### CODE REVIEW

**Comment by iNecas** [comment]
:+1: :)

**Comment by daviddavis** [comment]
Here's a forklift icon I made. Feel free to use it.

forklift

**Comment by iNecas** [comment]
Here you go https://github.com/Katello/forklift/pull/258, although I like the bitmap version a bit more :)

**Comment by ehelms** [comment]
Thanks @daviddavis ! I added it into the README, see example [1] but will need to change the code if the sizing looks good.


[1] https://github.com/ehelms/forklift/blob/285f7e496d8b45ea0e47ff5768ea8555629f69f5/README.md

**Comment by stbenjam** [comment]
ACK!

**Pull request merged**
