### PR TITLE
Fix missed rename capsule to foreman_proxy

### PR DESCRIPTION
**Pull request by iNecas**
I was hitting issues with running `vagrant hostmanager`, because
some boxes were referencing to non-existent boxes.

### CODE REVIEW

**Comment by ehelms** [comment]
Thoughts on updating the variable names her as well?

**Comment by iNecas** [comment]
Here you go :)

**Comment by stbenjam** [comment]
@iNecas Could you make rubocop :policewoman:  happy?

**Comment by iNecas** [comment]
Let's see what 👮 thinks now

**Comment by stbenjam** [comment]
Oh rubocop :roll_eyes:.  It's unhappy with `JSON.load`.

**Comment by ehelms** [comment]
@iNecas mind making the update to use `JSON.parse` here?

**Comment by iNecas** [comment]
I do mind but anyway: updated :D. I just accepted there is a law of conservation of happiness, so it can be either me or rubocop :)

**Comment by iNecas** [comment]
Updated

**Pull request merged**
