### PR TITLE
Capsule bats test is now proxy

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Currently preventing me from running bats on 3.3 tests

**Comment by ekohl** [comment]
Wasn't this fixed in https://github.com/Katello/forklift/commit/c7b53dc38c576c74d70174e49172c233f773e902?

**Comment by ekohl** [comment]
Looks like it was because https://github.com/Katello/forklift/commit/8c593d4e51fffe50eda93a5193e323b0f9e9f9ea is an empty commit.

**Comment by stbenjam** [comment]
Ah indeed it is.  The way github generates diffs is awful, it should should the diff of the commit against what would be merged in master.

**Pull request merged**
