### PR TITLE
Provide playbook to install Foreman core + platform plugins

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This provides two playbooks to install Foreman nightly or 1.12 with the following:

 * Foreman
 * Katello
 * Discovery
 * Bootdisk
 * Remote Execution
 * Hooks
 * Openscap
 * Docker
 * Tasks
 * Proxy -- Remote execution 
 * Proxy -- Openscap


Example:

```
vagrant up centos7
ansible-playbook -l centos7 playbooks/foreman_platform_1.12.yaml
```

**Comment by ehelms** [comment]
@jlsherrill or @stbenjam any thoughts on this?

**Comment by jlsherrill** [comment]
not a huge fan of the name 'platform', but can't really think of a better name.  Will test

**Comment by ehelms** [comment]
Me either but I was blanking on a better name other than something off the wall. I could change it to 'all in one' or 'warehouse' or 'pallet' or other

**Comment by stbenjam** [comment]
kitchensink?

**Comment by jlsherrill** [comment]
Functionality wise ACK.  I kinda like kitchensink, or maybe 'complete'

**Comment by ehelms** [comment]
Renamed to kitchensink since that got two votes

**Pull request merged**
