### PR TITLE
Pr/263

### PR DESCRIPTION
**Pull request by pronix**
small changes for use freeipa installation 
extend original PR from https://github.com/Katello/forklift/pull/263
also focused on nightly instead of stable release

### CODE REVIEW

**Comment by stbenjam** [comment]
It would be better to open an PR against @akofink's branch than another PR https://github.com/akofink/forklift

**Comment by stbenjam** [comment]
@pronix Ping - can you either rebase this PR or open one against @akofink's branch?

**Comment by pronix** [comment]
@stbenjam  is it what you want ? https://github.com/akofink/forklift/pull/1

**Comment by stbenjam** [comment]
Hi, thanks, this seems to work, ACK.

Thanks @akofink and @pronix !

**Pull request merged**
