### PR TITLE
Foreman and katello playbooks split into roles

### PR DESCRIPTION
**Pull request by tstrachota**
The idea behind this PR is to make setup more modular and enable easier configuration of foreman/katello with custom set of plugins. It should be backward compatible with original playbooks.

- new roles `foreman` and `katello`, original playbooks of the same name just require the new roles
- `katello_provisioning` split into foreman and katello part so that they can be used independently
- roles for plugins:
    - foreman_ansible
    - foreman_discovery
    - foreman_openscap
    - foreman_remote_execution
    - foreman_templates
- adds tags to tasks
- roles for seeding dummy hosts and users

### CODE REVIEW

**Comment by ehelms** [comment]
There are a lot of changes in this one PR that make it harder to deconstruct and analyze. Would you consider splitting the concepts up? Especially around how you are breaking down the roles into meta roles as a stand alone would help evaluate this approach against the original goals of composibility.

**Comment by stbenjam** [comment]
There's a lot of good things in here! Thanks! I agree with @ehelms, though, this PR is huge and there's a lot going on. I think the roles should be it's own PR, and the provisioning refactoring another.

**Comment by tstrachota** [comment]
I'm sorry for letting you wait. Sure, I'll split it into smaller chunks.

**Comment by tstrachota** [comment]
@ehelms @stbenjam I'm closing this PR in favour of:
- Move katello and foreman to roles https://github.com/Katello/forklift/pull/399
- Roles for installing plugins https://github.com/Katello/forklift/pull/398
- Roles for seeding data https://github.com/Katello/forklift/pull/397

**Pull request closed without merging**
