### PR TITLE
update how to start rails server

### PR DESCRIPTION
**Pull request by thomasmckay**
Specified path to rails as well as allowing server to be reached via http on port 3000

### CODE REVIEW

**Comment by jlsherrill** [comment]
Not opposed to this change, but any reason to not just hit  https://hostname/ ?

**Comment by jlsherrill** [comment]
Also is rails not in your bin path ?    bin/rails

[vagrant@robot ~]$ which rails
~/.rvm/gems/ruby-2.2.4/bin/rails

**Comment by thomasmckay** [comment]
If you don't think this is generically useful, I'm alright closing it. I run remote debugger and normally do so against :3000. I don't know if there are issues w/ https but I know I had problems in the distant past. I do not use rvm but yes rails is in my path; I just thought it was best practice to use path to rails.

**Comment by jlsherrill** [comment]
ACK

**Comment by thomasmckay** [comment]
I don't have merge permissions on this repo

**Pull request merged**
