### PR TITLE
Revert "Use foreman_installer_admin_password directly"

### PR DESCRIPTION
**Pull request by ehelms**
This reverts commit b6a850c39dc9e9146cd5139910ed3e6c1e58b158.

### CODE REVIEW

**Comment by ehelms** [comment]
@iNecas apologies, we need to revert your commit. When I reviewed it I was not thinking about the generalness of the foreman_installer role. By hard coding that option, we break any scenario that does not include foreman module (smart proxy, devel).

**Comment by ehelms** [comment]
This fixes -- https://github.com/Katello/forklift/issues/363

**Comment by ehelms** [comment]
This won't pass until https://github.com/Katello/forklift/pull/360 is merged

**Comment by dhx** [comment]
renamed to formean-initial-admin-password since:
https://github.com/theforeman/puppet-foreman/commit/81fcf11a48d3b5bee659e9a84c8927701e5d2674

**Pull request merged**
