### PR TITLE
disable system tests in bats

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
@stbenjam does this look right to you?

**Comment by stbenjam** [comment]
Oops, I opened https://github.com/Katello/forklift/pull/284

**Comment by stbenjam** [comment]
But to answer your question, you need to change it in the setup.rb installer options as well, looks like the InstallerOptionsProcessor is only used on dev environments? (https://github.com/stbenjam/katello-deploy/blob/5fd475330a59ca3fbd76ab360ee4a3340cc9bf38/lib/forklift/processors/installer_options_processor.rb#L11)

**Comment by jlsherrill** [comment]
i had it there and removed it based on what @ehelms said

**Comment by jlsherrill** [comment]
added back

**Comment by ehelms** [comment]
ACK

**Pull request merged**
