### PR TITLE
Make capsule selinux enablement configurable

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@beav care to take a look?

**Comment by ehelms** [comment]
@beav ping

**Comment by beav** [comment]
@ehelms I will test in a few, waiting on a few other items to finish running

**Comment by beav** [comment]
@ehelms sorry for the delay in review.

When I apply this on top of latest master, I get

```
TASK [common : Setup Foreman Repository] ***************************************
fatal: [centos7-capsule-3.0]: FAILED! => {"failed": true, "msg": "{{ version_map[katello_version] }}: {{ server.split('-')[-1] }}: {{ groups[server_group][0] }}: list object has no element 0"}

msg: {{ version_map[katello_version] }}: {{ server.split('-')[-1] }}: {{ groups[server_group][0] }}: list object has no element 0
        to retry, use: --limit @playbooks/capsule.retry
```

This appears to happen before selinux is disabled.

**Comment by stbenjam** [comment]
Need rebase

**Pull request closed without merging**
