### PR TITLE
Add playbooks to install Foreman and Katello

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This is a much larger change in scope, and I plan to do more updates to it to account for that including documentation. I debated doing a branch to encompass all of the changes this would entail as I cannot see how to do this in smaller chunks given all that setup.rb supports today.

**Comment by ehelms** [comment]
I changed the idea behind this PR to make it easier to pull in now. This will simply provides playbooks and roles to install Katello and Foreman and thus make transitioning to them easier in the future. So for now you can do:

```
vagrant up centos7
ansible-playbook playbooks/katello_nightly.yml
```

```
vagrant up centos7
ansible-playbook playbooks/foreman_nightly.yml
```

**Comment by stbenjam** [comment]
There seems to be missing a 'foreman' role, but I like the general idea here.

**Comment by ehelms** [comment]
Touche! I don't know where it went to, let me go find it.

**Comment by stbenjam** [comment]
One other thought I've wondered about, is the prefixing of variables. Is that an Ansible standard thing? It's a little annoying that we'd use things like capsule_skip_installer, katello_skip_installer, foreman_skip_installer, etc.

I've been playing around with getting host vars into the boxes.yaml, and it's a lot easier if it's just ONE variable name (skip_installer, use_koji_repos, etc) instead of having to think about the right prefix.

**Comment by stbenjam** [comment]
And that's not really something I think needs to be changed here, just wondering if it's something we might be able to do later or if there's a reason not to.

**Comment by ehelms** [comment]
AFAIK that is an Ansible best practice thing to do (scope variables to the role); however, we could achieve the best of both worlds by doing something like:

```
capsule_skip_installer: "{{ skip_installer || false }}"
```

This is completely untested but the general idea of an "inner scoped" variable that can also be set via a  generic variable.

**Comment by ehelms** [comment]
@stbenjam yea, so this is why it was missing -- https://github.com/Katello/forklift/pull/249/files#diff-a084b794bc0759e7a6b77810e01874f2L8

Foreman role should be there now

**Comment by ehelms** [comment]
As well, as you say, I'd prefer to look at the parameters thing after this as I want to use this as the basis for updating -- https://github.com/Katello/forklift/pull/248

**Comment by stbenjam** [comment]
ACK

**Pull request merged**
