### PR TITLE
Proposed restructure of Ansible content

### PR DESCRIPTION
**Pull request by ehelms**
Proposing this restructure to break things a part a bit and make them more discoverable/obvious in terms of what general area they focus on. This relates to my docs refactoring https://github.com/Katello/forklift/pull/262 

My goal is to get the repository cleaned up and more understandable as to it's goals and what it provides to begin broadcasting about it more broadly, with routine updates as we add functionality for the various use cases.

### CODE REVIEW

**Comment by iNecas** [comment]
works for me

**Comment by stbenjam** [comment]
Needs rebase

**Comment by ehelms** [comment]
I modified this a bit from my previous setup to more simply split up the Ansible concerns and put them under an Ansible directory.

**Comment by ekohl** [comment]
I wouldn't mind this change, but there's a merge conflict again.

**Pull request closed without merging**
