### PR TITLE
Fix broken dev box

### PR DESCRIPTION
**Pull request by stbenjam**
--disable-system-checks wasn't being added if user was using
default setup, it was only added if they changed devel-user.

### CODE REVIEW

**Comment by ekohl** [comment]
Tests are failing, otherwise :+1:

**Comment by stbenjam** [comment]
Green

**Comment by zjhuntin** [comment]
This worked really well for me!

**Comment by ehelms** [comment]
ACK

**Comment by lpramuk** [comment]
lib/forklift/processors/installer_options_processor.rb:5:in `process': undefined method `+' for nil:NilClass (NoMethodError)
	from ./setup.rb:107:in `<main>'

**Comment by stbenjam** [comment]
@lpramuk https://github.com/Katello/forklift/pull/288

**Pull request merged**
