### PR TITLE
Add foreman 1.13 to setup.rb versions

### PR DESCRIPTION
**Pull request by shlomizadok**
Trying to `vagrant up centos7-foreman-1.13` would fail without this :)

### CODE REVIEW

**Comment by shlomizadok** [comment]
(failure seem urelated)

**Comment by ekohl** [comment]
Maybe the Katello 3.2 version should be added as well?

**Comment by shlomizadok** [comment]
@ekohl - Added. Thanks!

**Comment by ehelms** [comment]
ACK - thanks @shlomizadok !

**Pull request merged**
