### PR TITLE
Add full testing playbooks for nightly and 3.1

### PR DESCRIPTION
**Pull request by ehelms**
The idea is to define a topology of boxes and versions to spin
up, install and then run some set of testing on with a single
command. This could be expanded in the future to encompass upgrade
or simply capturing more complex topologies of Katello installations

### CODE REVIEW

**Comment by ehelms** [comment]
To run:

ansible-playbook playbooks/pipeline_katello_31.yml

**Comment by ekohl** [comment]
There's a merge conflict

**Comment by ehelms** [comment]
@ekohl updated

**Comment by ehelms** [comment]
@stbenjam That is a valid point, I think my changes from https://github.com/Katello/forklift/pull/249 would help facilitate that better because right now the Capsule isn't setup to use koji repos.

**Comment by ehelms** [comment]
This PR has been updated based on the latest rebase to master.

**Comment by ehelms** [comment]
@stbenjam or @jlsherrill a review of this would be greatly appreciated so I can continue building on top of it.

**Comment by stbenjam** [comment]
Looks ok from a code perspective. I've got a pipeline running right now, but I suppose it will take some time to complete.

One thought - would you want to include a pipeline_katello_koji playbook? That'd address the comment I had in https://github.com/Katello/forklift/pull/248#issuecomment-232373362? Not required, but looking at this PR I have some ideas, namely if this was actually used for bats - and increase BATs coverage to include capule-related tasks.

**Comment by ehelms** [comment]
@stbenjam I don't mind making this use koji by default

**Comment by ehelms** [comment]
I updated to set use katello koji repositories by default.

**Comment by stbenjam** [comment]
Awesome, and my run just finished successfully :100: 

ACK

**Pull request merged**
