### PR TITLE
Add qemu as the libvirt driver

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by ekohl** [comment]
In which case is this needed? Does your libvirt have multiple drivers?

**Comment by pronix** [comment]
there are "kvm" and "qemu". but qemu much slower, if it is not qemu-kvm :)
better no specify and use default libvirtd configured  driver

**Comment by cfouant** [comment]
@ekohl - I've got both kvm and qemu. Just did a fresh provisioning and got the following error:

`Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: invalid argument: could not find capabilities for domaintype=kvm`

**Comment by stbenjam** [comment]
What does this return for you?

```
egrep -c '(vmx|svm)' /proc/cpuinfo
```

Sounds like you don't have virt acceleration enabled

**Comment by cfouant** [comment]
@stbenjam could be the case, I had to trade in my laptop. That command returns 4.

**Comment by ekohl** [comment]
That sounds like KVM should work. Is it possible you're also running VirtualBox? In the past I've seen that claim the CPUs for visualization and prevented KVM from loading. You really really want KVM rather than Qemu for performance reasons.

**Comment by cfouant** [comment]
@ekohl @stbenjam enabling virtualization in bios worked. I thought it was a regression as the new  laptop was supposed to have mirrored configuration. Closing. Thanks!

**Pull request closed without merging**
